services:
  - type: web
    name: poultry-system
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: GMAIL_USER
        sync: false
      - key: GMAIL_APP_PASSWORD
        sync: false
      - key: OWNER_EMAIL
        sync: false
      - key: PORT
        value: 3000
      - key: JWT_SECRET
        sync: false
